name: CI Pipeline

on:
  push:
    branches:
      - '**'                 
  workflow_dispatch:      
  repository_dispatch:      
  schedule:
    - cron: '0 0 * * *'    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run Lefthook (lint + format + test)
        run: npx lefthook run pre-commit

      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  build:
    runs-on: ubuntu-latest
    needs: test      
    steps:           
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: node-modules

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
